# Generated by Django 3.0.2 on 2020-01-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(default='AZE', max_length=3)),
                ('lang_name', models.CharField(max_length=20)),
            ],
        ),
    ]
